[package]
name = "day_11"
version = "0.1.0"
authors = ["Jeremy Borgman <borgman.jeremy@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.20.0"
strum_macros = "0.20"